action_id: trunk-share-with-everyone
date: 2024-03-18 16:45:36
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1710780336
full_timestamp:
  nanos: 30512000
  seconds: 1710780336
trunk_version: 1.21.0
